### ISSUE TITLE
YouTube scherm terugknop werkt niet

### ISSUE THREAD

**Issue by Krotau** [Krotau/Pergamijn#1]
Heb gekeken in de code en volgens mij moet hij het doen maar zodra ik het op mijn telefoon uitprobeer werkt het niet.

code:

```
namespace Pergamijn
{
    public partial class YouTube : ContentPage
    {
        public YouTube()
        {
            InitializeComponent();
        }

        void OnTapGestureRecognizerBack(object sender, EventArgs args)
        {
            var imageSender = (Image)sender;
            // Do something

            Navigation.PopModalAsync();
        }

        void OnTapVideoYoutube(object sender, EventArgs args)
        {
            var imageSender = (Image)sender;
            // Do something

            Navigation.PushAsync(new Videoplayer());
        }
    }
}
```

**Comment by LowProgram** [comment]
Klopt idd, dit is de code wat jij mij bij heb gebracht en ook gebruikt hebt in 'Netflix'. Heb de code nogmaal na gekeken, maar het button gedeelte moet zowel bij deze als bij de Remote kloppen. Dus misschien iets mis ind die code wat jij stuurde of in het daadwerkelijke android deel? Misschien een idee om dit ook aan Ken en Jim voor te leggen?

**Comment by LowProgram** [comment]
Het ziet eruit dat het probleem op gelost is. 
Wat er gebeurde is dat er over de knop een "still image" geprojecteerd werd. Dit zorgde ervoor dat de knop niet meer bereikbaar was. 

Zie de code:
Oud:


            <Image Source="@drawable/Backbutton.png" Grid.Row="1" Grid.ColumnSpan="2" Grid.Column="1"/>
            <Image Source="@drawable/Zoekbalk.png" Grid.Row="1" Grid.ColumnSpan="3"  Grid.Column="2"/>
            <Image Source="@drawable/Favorite.png" Grid.Row="1" Grid.Column="5"/>
            <Image Source="@drawable/Youtube.png" Grid.Row="2" Grid.ColumnSpan="2" Grid.Column="2"/>
            <Image Source="@drawable/Youtube.png" Grid.Row="2" Grid.ColumnSpan="2" Grid.Column="3"/>
            <Image Source="@drawable/Youtube.png" Grid.Row="3" Grid.Column="2"/>
            <Image Source="@drawable/Youtube.png" Grid.Row="3" Grid.Column="3"/>
            <Image Source="@drawable/Youtube.png" Grid.Row="3" Grid.Column="4"/>
            <Image Source="@drawable/VorigeKnop.png" Grid.Row="4" Grid.ColumnSpan="2" Grid.Column="2"/>
            <Image Source="@drawable/MeerKnop.png" Grid.Row="4"  Grid.ColumnSpan="2"  Grid.Column="3"/>


Nieuw:

```
            <Image Source="@drawable/Zoekbalk.png" Grid.Row="1" Grid.ColumnSpan="3"  Grid.Column="2"/>
            <Image Source="@drawable/Favorite.png" Grid.Row="1" Grid.Column="5"/>
            <Image Source="@drawable/Youtube.png" Grid.Row="2" Grid.ColumnSpan="2" Grid.Column="3"/>
            <Image Source="@drawable/Youtube.png" Grid.Row="3" Grid.Column="2"/>
            <Image Source="@drawable/Youtube.png" Grid.Row="3" Grid.Column="3"/>
            <Image Source="@drawable/Youtube.png" Grid.Row="3" Grid.Column="4"/>
            <Image Source="@drawable/VorigeKnop.png" Grid.Row="4" Grid.ColumnSpan="2" Grid.Column="2"/>
            <Image Source="@drawable/MeerKnop.png" Grid.Row="4"  Grid.ColumnSpan="2"  Grid.Column="3"/>
```


Daarnaast stond er een foute functie in het Youtube.xaml.cs zijn. 
Bij de forward button `Navigation.PushAsync(new Videoplayer());` in plaats van `Navigation.PushModalAsync(new Videoplayer());` stond
